### ISSUE TITLE
TODO before X-mas

### ISSUE THREAD

**Issue by anadis504** [rage/factor-analysis-exercise-service#28]
- global variables references 
  - [x]  create reference in edit-exercise
  - [x] show reference in answer-exercise (factorial/non-factorial) info - and infoheader-elements
  - [x] figure out how to use them in submission view? hard-coded? Enable teacher to design submission view usning the variables?
- vector normalization (factorial)
  - [x] edit-view upload .cvs file for distribution normalization (mean/scale)
  - [x]  add numbers to matrix (visualizitaion)
  - [x] use numbers in factor report calculations and NaN-values imputations
- Implement max NaN answers
  - [x] edit-exercise has assert max-NaN limit
  - [x] utilize
- Submission view layout
  - [x] implement accordion
  - [x] discuss with group what else they need:
    - [x] Create a title for submission page
    - [x] create default message for factorial report with too many nans (could not provide report etc)
    - [x] breeds not in list or without values are not shown
    - [x] maybe make info elements with larger text (too discrete atm) 
- Breed avg, possible before X-mas? 
  - [x] .csv file upload + parse + utilize into report (YES)
- [x] UPDATE TESTS 
- [ ] #34
